version: '3.8'

services:
  web:
    build: .
    ports:
      - "3050:3000"
    volumes:
      - .:/app
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/user_crud_app

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27050:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
